config/routes.rb
Rails.application.routes.draw do
  root 'posts#landing'
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments do
      :create
      collection do
        patch :destroy
      end
    end
    resources :likes
  end
  resources :pets do
    resources :favors
  end
  resources :users, only: :show
  resources :recommendations, only: [:index]

# Routes for Google authentication
#get ‘auth/:provider/callback’, to: ‘sessions#googleAuth’
#get ‘auth/failure’, to: redirect(‘/’)
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favor.rb
class Favor < ApplicationRecord
  belongs_to :pet
  belongs_to :user

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :actor, class_name: "User"
  belongs_to :notifiable, polymorphic: true

  scope :unread, -> { where(read_at: nil) }
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :posts
  has_many :pictures
  has_many :favors, dependent: :destroy
  has_many :users, through: :favors

end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :picture, PictureUploader
  belongs_to :user
  belongs_to :post
  belongs_to :pet

end

app/models/post.rb
class Post < ApplicationRecord
  scope :timeline, ->(user) { where(user: user) }
  mount_uploader :picture, PictureUploader
  
  has_many :comments
  has_many :pictures
  belongs_to :user
  belongs_to :pet
  has_many :likes, dependent: :destroy
  has_many :users, through: :comments
  has_many :users, through: :likes

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_writer :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :trackable, :authentication_keys => {email: true, login: false}

  has_many :comments
  has_many :posts
  has_many :pictures
  has_many :pets
  has_many :likes, dependent: :destroy
  has_many :favors, dependent: :destroy
  has_many :notifications, foreign_key: :recipient_id

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "Already liked!"
    else
      @post.likes.create(user_id: current_user.id)
      if current_user != @post.user
        Notification.create(recipient: @post.user, actor: current_user, action: "liked", notifiable: @post)
      end
    end
    redirect_to post_path(@post)
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "You have not liked this post. Cannot unlike."
    else
      @like.destroy
    end
    redirect_to post_path(@post)
  end

  private

  def already_liked?
    Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_like
    @like = @post.likes.find(params[:id])
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user

    respond_to do |format|
      if @pet.save
        new_petId = @pet.id
        petId = current_user.pet_id
        petId << new_petId
        current_user.pet_id = petId
        current_user.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :breed, :species)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except:[:landing]

  def index
    @posts = Post.timeline(current_user).order('created_at DESC').paginate(page: params[:page], per_page: 10)
  end

  def landing
    # Pull most recent 15 posts from db
    last_ten = Post.last(15);
    #randomly choose 3 posts to display
    @random_posts = last_ten.sample(3);
  end

  def new
    @posts = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @username = @post.user.username
    @pet = @post.pet_id
  end

  def create
    @post = current_user.posts.create(post_params)
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id, :pet_id, :picture, :video)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @pets = Pet.includes(:posts).where(user_id: @user)
    @favors = @user.favors.count
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favors_helper.rb
module FavorsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pets/_form.html.erb
<%= simple_form_for(@pet) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :breed %>
    <%= f.select :species, ['cat','dog','bird','mythical'] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Breed</th>
      <th>Species</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.user_id %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.species %></td>
        <td><%= pet.favors.count %> Favors</td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @pet.user_id %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Species:</strong>
  <%= @pet.species %>
</p>

<% pre_favor = @pet.favors.find { |favor| favor.user_id == current_user.id} %>
<% if pre_favor %>
  <%= link_to pet_favor_path(@pet, pre_favor), method: :delete do %>
    UnFavor
  <% end %>
<% else %>
  <%= link_to pet_favors_path(@pet), method: :post do %>
    <i class="fa fa-paw"></i>
    High Paw - Favor this pet!
  <% end %>
<% end %>
<p><%= @pet.favors.count %> Favor(s)</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

app/views/posts/_post.html.erb
<div class='each-post'>

  <div class="image-box-index">
      <% if false %>
      Commenting this part out for photo uploading later

        <% if post.photos.present? %>
          <%= image_tag @photo_url.to_s.last %>
        <% end %>

      <% end %>
  </div>

  <div class="paw-index">
    <i class="fa fa-paw"></i>
  </div>

  <div class="comment-index">
    <%= link_to post_path(post) do %>
      <i class="fa fa-comments"></i>
    <% end %>
  </div>

  <div class="like-box-index">
    <p><%= post.likes.count %> Like(s)</p>
  </div>

  <div class="created-at-box-index">
    <p><%= post.created_at.strftime("%B, %d %Y, %l:%M%P") %></p>
  </div>

  <div class="content-box-index">
    <h5><%= link_to post.content, post_path(post) %></h5>
  </div>

</div>

app/views/posts/index.html.erb
<h1>Posts Page right after Signup</h1>
<h2>My Posts</h2>

<div id='posts-container'>
  <%= render @posts %>
</div>

<hr />
<body>
  <div class="col-10 offset-1 row" id='posts-index'>
    <% @posts.each do |post| %>
      <div class="post-container">
        <div class="float-left">
          <%= image_tag post.picture.to_s, class: 'post-picture' %>
        </div>
        <div class="post-content">
          <h5><%= link_to '@' + post.pet.name, post_path(post), class: 'post-username' %></h5>
          <%= link_to post_likes_path(post), method: :post do %>
            <i class="fa fa-paw fa-2x"></i>
          <% end %>
          <%= link_to post_path(post) do %>
            <i class="fa fa-comment fa-2x"></i>
          <% end %>
          <br />
          <p><%= post.content %></p>
        </div>
        <br />
        <br />
      </div>
    <% end %>
  </div>
</body>

app/views/posts/index.js.erb
$('#posts').append('<%= j render(@posts) %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/posts/landing.html.erb
<body>  
  <div class="container"> 
    <h1 id="greeting">Hello, Human. Check out these good pets.</h1>
    <br /> 
    <div class="row">

      <!-- Landing posts -->
      <div class="row landing-posts-container"> 
        <% @random_posts.each do |post| %>
          <div class="col-sm-4 landing-post">
            <%= image_tag post.picture.to_s, class: "landing-post-pic" %>
            <h3><%= post.content %></h3> 
            <h5><%= post.user.username %></h5>
          </div> 
        <% end %>
      </div>  
    </div>  
  </div>  
</body>

app/views/posts/new.html.erb
<body>  
  <div class="new-post-container col-8 offset-2 col-12-sm offset-0-sm">
    <div class="new-post-content col-10 offset-1">
      <h1>Create a Post</h1>
      <br />

      <%= simple_form_for @posts do |f| %>
        <h5>Pick your pet: <%= f.collection_select :pet_id, Pet.where(:user_id => current_user.id), :id, :name %></h5>

        <br />

        <h5><%= f.input :content, label: 'Add content: ' %></h5>

        <br />
     
        <h5 id="create-post-picture-field"><%= f.input :picture, label: 'Add a picture: ' %></h5>

        <br />
        <br />

        <%= f.submit 'Create', class: 'btn btn-dark btn-lg', id: 'create-post-btn' %>
        <br />
      <% end %>
    </div>
  </div>
</body>

app/views/posts/show.html.erb
<body>
  <div class="col-10 offset-1 row">
    <h1><%= link_to '@' + @post.pet.name, pet_path(@pet) %></h1>

    <div class="float-right">
      <%= image_tag @post.picture.to_s, class: 'post-show-picture' %>
    </div>

    <div class="show-post-content">
      <h5><%= @post.content %></h5>

      <p>Posted by <%= @post.user.username %></p>

      <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
      <% if pre_like %>
        <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
      <% else %>
        <%= button_to 'Like', post_likes_path(@post), method: :post %>
      <% end %>
      <p><%= @post.likes.count %> Like(s)</p>

      <h3>Comments</h3>

      <% @post.comments.each do |comment| %>
        <blockquote>
          <b><%= comment.message %></b>
            <%= comment.user.username %>
        </blockquote>
      <% end %>

      <br />

      <div>
        <%= simple_form_for @comment, url: post_comments_path(@post) do |f| %>
          <%= f.input :message %>
          <%= f.submit "Add a comment" %>
        <% end %>
      </div>
    </div>
  </div>

  <br /><br />

</body>

app/views/users/show.html.erb
<body>
  <div class="container-fluid">
    <!-- Edit button for users viewing own profile -->
    <% if current_user === @user %>
      <%= link_to edit_user_registration_path do %>
        <button type="button" class="btn btn-dark float-right">Edit</button>
      <% end %>
    <% end %>

    <div id="user-info">
      <h1><%= @user.username %></h1>
      <h5><%= @favors %> Pets Favored</h5>
      <% if current_user === @user %>
        <%= link_to new_pet_path do %>
          <button type="button" class="btn btn-dark btn-lg">+ Pet</button>
        <% end %>
      <% end %>
    </div>

    <!-- Create cards for each pet -->
    <div class="row" id="profile-pets">
      <% @pets.each do |pet| %>
        <div class="card col-6-lg col-10-sm offset-1-sm text-center border-light rounded pet-info">
          <div class="card-body">
            <h3 class="card-title pet-name">@<%= link_to pet.name, pet_path(pet) %></h3>
            <% if current_user === @user %>  
              <%= link_to new_post_path do %>
                <button type="button" class="btn btn-dark add-post">+ Post</button>
              <% end %>
            <% end %>

            <!-- Create cards for last 4 posts -->
            <div class="row card-deck" id="pet-posts">
              <% pet.posts.last(4).each do |post| %>
                <div class="card profile-posts col-6-lg col-12-md text-center border-light">
                  <div class="card-body">
                    <%= image_tag post.picture.to_s, class: "profile-post-pic" %>
                    <p class="post-content"><%= post.content %></p>
                  </div>
                </div>
              <% end %>
            </div>

          </div>
        </div>
      <% end %>
    </div>

    <br />
    <br />

  </div>
</body> 