config/routes.rb
Rails.application.routes.draw do
  root 'posts#landing'
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments do
      :create
      collection do
        patch :destroy
      end
    end
    resources :likes
  end
  resources :pets do
    resources :favors
  end
  resources :users, only: :show
  resources :recommendations, only: [:index]

# Routes for Google authentication
#get ‘auth/:provider/callback’, to: ‘sessions#googleAuth’
#get ‘auth/failure’, to: redirect(‘/’)
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favor.rb
class Favor < ApplicationRecord
  belongs_to :pet
  belongs_to :user

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :actor, class_name: "User"
  belongs_to :notifiable, polymorphic: true

  scope :unread, -> { where(read_at: nil) }
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :posts
  has_many :pictures
  has_many :favors, dependent: :destroy
  has_many :users, through: :favors

end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :picture, PictureUploader
  belongs_to :user
  belongs_to :post
  belongs_to :pet

end

app/models/post.rb
class Post < ApplicationRecord
  scope :timeline, ->(user) { where(user: user) }
  mount_uploader :picture, PictureUploader
  
  has_many :comments
  has_many :pictures
  belongs_to :user
  belongs_to :pet
  has_many :likes, dependent: :destroy
  has_many :users, through: :comments
  has_many :users, through: :likes

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_writer :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :trackable, :authentication_keys => {email: true, login: false}

  has_many :comments
  has_many :posts
  has_many :pictures
  has_many :pets
  has_many :likes, dependent: :destroy
  has_many :favors, dependent: :destroy
  has_many :notifications, foreign_key: :recipient_id

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "Already liked!"
    else
      @post.likes.create(user_id: current_user.id)
      if current_user != @post.user
        Notification.create(recipient: @post.user, actor: current_user, action: "liked", notifiable: @post)
      end
    end
    redirect_to post_path(@post)
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "You have not liked this post. Cannot unlike."
    else
      @like.destroy
    end
    redirect_to post_path(@post)
  end

  private

  def already_liked?
    Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_like
    @like = @post.likes.find(params[:id])
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user

    respond_to do |format|
      if @pet.save
        new_petId = @pet.id
        petId = current_user.pet_id
        petId << new_petId
        current_user.pet_id = petId
        current_user.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :breed, :species)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except:[:landing]

  def index
    @posts = Post.timeline(current_user).order('created_at DESC').paginate(page: params[:page], per_page: 10)
  end

  def landing
    # Pull most recent 15 posts from db
    last_ten = Post.last(15);
    #randomly choose 3 posts to display
    @random_posts = last_ten.sample(3);
  end

  def new
    @posts = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @username = @post.user.username
    @pet = @post.pet_id
  end

  def create
    @post = current_user.posts.create(post_params)
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id, :pet_id, :picture, :video)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favors_helper.rb
module FavorsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetsBeSocial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=PT+Sans&display=swap" rel="stylesheet">
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-dark">
      <button class="navbar-toggler" type="button" data-behavior="notifications-link" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Create Post", new_post_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Pets to Follow", recommendations_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#">Notifications</a>
          </li>
        </ul>
        <%= link_to "Pets Be Social", root_path, class: 'navbar-brand navbar-brand-centered' %>
      </div>

      <ul class="navbar-nav mr-auto logins">
        <% if user_signed_in? %>
          <li class="nav-item btn-group" data-behavior="notifications">
            <a class="dropdown-toggle nav-link" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon "bell" %> <span data-behavior="unread-count"></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu1" data-behavior="notification-items">
              <!--  
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
              -->
            </div>
          </li>
          <li class="nav-item active">
            <%= link_to 'Profile', user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="footer">
      <h6 id="build-credit"><%= link_to 'Build by Mia, Melanie + Kevin', 'https://github.com/FinalProjectUCBerkleyAug/final_project' %></h6>
    </div>
    <%= yield %>
  </body>
</html>